- hosts: master
  gather_facts: false
  become: yes
  vars_files:
    - serverConf.yml
    
  tasks:
    - name: Remove /etc/containerd/config.toml
      file:
        path: /etc/containerd/config.toml
        state: absent
        
    - name: Restart containerd
      service:
        name: containerd
        state: restarted

    - name: Reset kubeadm
      shell: kubeadm reset --force
      ignore_errors: yes

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket /run/containerd/containerd.sock
      args:
        chdir: $HOME

    - name: Create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config, set mode as 0600 to avoid helm warning
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        mode: '0600'
        remote_src: yes

    - name: Install Pod networkhistory
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
