---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: dashboard
  namespace: kube-system
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{adminEmail}}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: dashboard
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class:  nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-ingress
  namespace: kube-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #     ingressClass, this annotations used in v1.23
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "dashboard"
spec:
  tls:
    - hosts:
        - {{k8HostName}}
      secretName: dashboard-ingress-secret
  rules:
    - host: {{k8HostName}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443